server:
  port: 9901
test:
  properties:
    desc: ceshi
    user-infos:
      - name: zhangsan
        address: 99
      - name: lisi
        address: 88
    commons:
      - aaa
      - bbb
      - ccc



