spring:
  application:
    name: boot-approve
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.13.10:3306/boot-approve?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  #mybatis-plus:
  #  type-aliases-package: com.example.boot.approve.mapper
  #  configuration:
  #    map-underscore-to-camel-case: true #驼峰自动映射
  #    lazy-loading-enabled: true
  #    multiple-result-sets-enabled: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 日志控制级别
  #  global-config:
  #    banner: false
  #    db-config:
  #      id-type: ASSIGN_ID
  #      table-underline: true
  #  mapper-locations: classpath*:/mapper/**/*.xml


mybatis-plus:
  type-aliases-package: com.example.boot.approve
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      table-underline: true