spring:
  application:
    name: boot-approve
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.13.10:3306/boot-approve?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root