server:
  port: 8080

spring:
  application:
    name: boot-flowable
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
    url: jdbc:mysql://192.168.13.10:3306/boot-flowable?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

flowable:
  async-executor-activate: false #关闭定时任务job
  database-schema-update: false # 当flowable 发现库与数据库表结构不一致的时候， 会自动将数据库表结构升级为最新版本 flowable升级需要
  common:
    app:
      idm-url: http://localhost:8080/expense
  idm:
    app:
      admin:
        user-id: admin
        password: test
        first-name: admin
        last-name: admin
  rest:
    app:
      authentication-mode: verify_privilege
  modeler:
    app:
      rest-enabled: true
server:
  servlet:
    context-path: /expense

